model_name = './models/model.hdf5'
models_path = './models'
input_shape = (300, 300, 3)
images_folder = './dataset/images'
test_images_folder = './dataset/images'
images_count = 718
epoch = 1
batch = 10
emb_size = 64
